### ISSUE TITLE
Načítat velikost kolekce dynamicky

### ISSUE THREAD

**Issue by FilipJirsak** [MCHCortana/j2w-ukol2#1]
https://github.com/MCHCortana/j2w-ukol2/blob/6ff3e7a1baacdc9b6bf198e4e630d6d63c7c08d4/src/main/java/cz/czechitas/java2webapps/ukol2/controller/MainController.java#L43-L44

Tady by bylo lepší použít velikost kolekce. Když by se změnil seznam citátů nebo obrázků, nebude potřeba tady pak měnit čísla ručně (na což by se nejspíš zapomnělo).

**Comment by MCHCortana** [comment]
Díky opraveno.
